// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/ActiveRingChart/docs/demo.vue')['default']
    Demo2: typeof import('./src/components/DigitalFlop/docs/demo2.vue')['default']
    Demo3: typeof import('./src/components/DigitalFlop/docs/demo3.vue')['default']
    Demo4: typeof import('./src/components/DigitalFlop/docs/demo4.vue')['default']
    DvMenu: typeof import('./src/components/DvMenu.vue')['default']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
